CALORIE_MODE = "calorie"
QNA_MODE = "nutrition_qa"
UNKNOWN_MODE = "unknown"

HIGH_CONFIDENCE = "HIGH"
MEDIUM_CONFIDENCE = "MEDIUM"
LOW_CONFIDENCE = "LOW"
CALORIE_MODE = "calorie"
QNA_MODE = "nutrition_qa"
UNKNOWN_MODE = "unknown"

HIGH_CONFIDENCE = "HIGH"
MEDIUM_CONFIDENCE = "MEDIUM"
LOW_CONFIDENCE = "LOW"